services:
  - type: web
    name: fsadprobackend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_HOST
        fromDatabase:
          name: fsad_db
          property: host
      - key: DB_USER
        fromDatabase:
          name: fsad_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: fsad_db
          property: password
      - key: DB_NAME
        value: fsad_db
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

databases:
  - name: fsad_db
    databaseName: fsad_db
    plan: free
